services:
  db:
    image: postgres:17.4-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gonote
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db: 
    image: postgres:17.4-alpine
    container_name: test_database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gonote_test

volumes:
  pgdata:
