services:
  db:
    image: postgres:17.4-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gonote
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
